### ISSUE TITLE
msg="proxy 10: ss 172.67.69.236:443 initialize error: unknown method: 1ca7e43f-a737-4667-948e-67c2059f82e9"

### ISSUE THREAD

**Issue by langziyang** [ts-sf/fly#4]
msg="proxy 10: ss 172.67.69.236:443 initialize error: unknown method: 1ca7e43f-a737-4667-948e-67c2059f82e9"

**Comment by glIrving** [comment]
me too

**Comment by ts-sf** [comment]
what client?

**Comment by langziyang** [comment]
openclash

**Comment by langziyang** [comment]
openclash

**Comment by ts-sf** [comment]
Have you tried using the latest clash subscription?

**Comment by glIrving** [comment]
我用的windows 的 clash verge 导入的最新的订阅 到了这条就报错了 "name":"未知3","type":"ss","server":"104.18.10.128","port":2083,"cipher":"d342d11e-d424-4583-b36e-524ab1f0afa4","alterId":0,"tls":true,"password":"","skip-cert-verify":true}

**Comment by langziyang** [comment]
2024-06-26 17:29:34 level=error msg="proxy 2: ss 104.18.10.128:2083 initialize error: unknown method: d342d11e-d424-4583-b36e-524ab1f0afa4"

**Comment by ts-sf** [comment]
Try again? 

> 2024-06-26 17:29:34 level=error msg="proxy 2: ss 104.18.10.128:2083 initialize error: unknown method: d342d11e-d424-4583-b36e-524ab1f0afa4"



> 我用的windows 的 clash verge 导入的最新的订阅 到了这条就报错了 "name":"未知3","type":"ss","server":"104.18.10.128","port":2083,"cipher":"d342d11e-d424-4583-b36e-524ab1f0afa4","alterId":0,"tls":true,"password":"","skip-cert-verify":true}

**Comment by langziyang** [comment]
![image](https://github.com/ts-sf/fly/assets/2345387/b08bda07-716c-4940-9210-842e0d0be095)
